# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
right_format = '$cmd_duration $time'

[git_branch]
style = 'bold purple'
format = '[$branch(:$remote_branch)]($style) '

[terraform]
format = 'via [$symbol$workspace]($style) '
